const weatherUrl = {
    day: {
        "Cloudy": "/weatherIcons/cloudy.webp",
        "Overcast": "/weatherIcons/cloudy.webp",
        "Mist": "/weatherIcons/cloudy.webp",
        "Fog": "/weatherIcons/cloudy.webp",
        "Light rain": "/weatherIcons/light-rain.webp",
        "Moderate rain": "/weatherIcons/moderate-rain.webp",
        "Heavy rain": "/weatherIcons/heavy-rain.webp",
        "Moderate or heavy freezing rain": "/weatherIcons/light-freezing-rain.webp",
        "Light freezing rain": "/weatherIcons/light-freezing-rain.webp",
        "Light sleet": "/weatherIcons/light-freezing-rain.webp",
        "Moderate or heavy sleet": "/weatherIcons/light-freezing-rain.webp",
        "Light sleet showers": "/weatherIcons/light-freezing-rain.webp",
        "Moderate or heavy sleet showers": "/weatherIcons/light-freezing-rain.webp",
        "Patchy sleet possible": "/weatherIcons/patchy-sleet-possible.webp",
        "Patchy freezing drizzle possible": "/weatherIcons/ight-freezing-rain.webp",
        "Freezing drizzle": "/weatherIcons/ight-freezing-rain.webp",
        "Heavy freezing drizzle": "/weatherIcons/ight-freezing-rain.webp",
        "Blowing snow": "/weatherIcons/blowing-snow.webp",
        "Blizzard": "/weatherIcons/blizzard.webp",
        "Freezing fog": "/weatherIcons/freezing-fog.webp",
        "Patchy light drizzle": "/weatherIcons/patchy-light-drizzle.webp",
        "Light drizzle": "/weatherIcons/patchy-light-drizzle.webp",
        "Light snow": "/weatherIcons/light-snow.webp",
        "Moderate snow": "/weatherIcons/moderate-snow.webp",
        "Heavy snow": "/weatherIcons/heavy-snow.webp",
        "Ice pellets": "/weatherIcons/light-snow.webp",
        
        "Sunny": "/weatherIcons/day/sunny.webp",
        "Partly cloudy": "/weatherIcons/day/partly-cloudy.webp",
        "Patchy rain possible": "/weatherIcons/day/patchy-rain-possible.webp",
        "Patchy light rain": "/weatherIcons/day/patchy-rain-possible.webp",
        "Light rain shower": "/weatherIcons/day/light-rain-shower.webp",
        "Moderate rain at times": "/weatherIcons/day/moderate-rain-at-times.webp",
        "Moderate or heavy rain shower": "/weatherIcons/day/heavy-rain-at-times.webp",
        "Heavy rain at times": "/weatherIcons/day/heavy-rain-at-times.webp",
        "Torrential rain shower": "/weatherIcons/day/torrential-rain-shower.webp",
        "Patchy light rain with thunder": "/weatherIcons/day/patchy-light-rain-with-thunder.webp",
        "Moderate or heavy rain with thunder": "/weatherIcons/day/moderate-or-heavy-rain-with-thunder.webp",

        "Patchy snow possible": "/weatherIcons/day/patchy-snow-possible.webp",
        "Patchy light snow": "/weatherIcons/day/patchy-snow-possible.webp",
        "Light snow showers": "/weatherIcons/day/patchy-snow-possible.webp",
        "Thundery outbreaks possible": "/weatherIcons/day/thundery-outbreaks-possible.webp",
        "Patchy moderate snow": "/weatherIcons/day/patchy-moderate-snow.webp",
        "Moderate or heavy snow showers": "/weatherIcons/day/patchy-moderate-snow.webp",
        "Light showers of ice pellets": "/weatherIcons/day/patchy-moderate-snow.webp",
        "Patchy heavy snow": "/weatherIcons/day/patchy-heavy-snow.webp",
        "Moderate or heavy showers of ice pellets": "/weatherIcons/day/patchy-heavy-snow.webp",
        "Patchy light snow with thunder": "/weatherIcons/day/patchy-light-snow-with-thunder.webp",
        "Moderate or heavy snow with thunder": "/weatherIcons/day/moderate-or-heavy-snow-with-thunder.webp",

    },

    night: {
        "Cloudy": "/weatherIcons/cloudy.webp",
        "Overcast": "/weatherIcons/cloudy.webp",
        "Mist": "/weatherIcons/cloudy.webp",
        "Fog": "/weatherIcons/cloudy.webp",
        "Light rain": "/weatherIcons/light-rain.webp",
        "Moderate rain": "/weatherIcons/moderate-rain.webp",
        "Heavy rain": "/weatherIcons/heavy-rain.webp",
        "Moderate or heavy freezing rain": "/weatherIcons/light-freezing-rain.webp",
        "Light freezing rain": "/weatherIcons/light-freezing-rain.webp",
        "Light sleet": "/weatherIcons/light-freezing-rain.webp",
        "Moderate or heavy sleet": "/weatherIcons/light-freezing-rain.webp",
        "Light sleet showers": "/weatherIcons/light-freezing-rain.webp",
        "Moderate or heavy sleet showers": "/weatherIcons/light-freezing-rain.webp",
        "Patchy sleet possible": "/weatherIcons/patchy-sleet-possible.webp",
        "Patchy freezing drizzle possible": "/weatherIcons/ight-freezing-rain.webp",
        "Freezing drizzle": "/weatherIcons/ight-freezing-rain.webp",
        "Heavy freezing drizzle": "/weatherIcons/ight-freezing-rain.webp",
        "Blowing snow": "/weatherIcons/blowing-snow.webp",
        "Blizzard": "/weatherIcons/blizzard.webp",
        "Freezing fog": "/weatherIcons/freezing-fog.webp",
        "Patchy light drizzle": "/weatherIcons/patchy-light-drizzle.webp",
        "Light drizzle": "/weatherIcons/patchy-light-drizzle.webp",
        "Light snow": "/weatherIcons/light-snow.webp",
        "Moderate snow": "/weatherIcons/moderate-snow.webp",
        "Heavy snow": "/weatherIcons/heavy-snow.webp",
        "Ice pellets": "/weatherIcons/light-snow.webp",



        "Clear": "/weatherIcons/night/clear.webp",
        "Partly cloudy": "/weatherIcons/night/partly-cloudy.webp",
        "Patchy rain possible": "/weatherIcons/night/patchy-rain-possible.webp",
        "Patchy light rain": "/weatherIcons/night/patchy-rain-possible.webp",
        "Light rain shower": "/weatherIcons/night/light-rain-shower.webp",
        "Moderate rain at times": "/weatherIcons/night/moderate-rain-at-times.webp",
        "Moderate or heavy rain shower": "/weatherIcons/night/heavy-rain-at-times.webp",
        "Heavy rain at times": "/weatherIcons/night/heavy-rain-at-times.webp",
        "Torrential rain shower": "/weatherIcons/night/torrential-rain-shower.webp",
        "Patchy light rain with thunder": "/weatherIcons/night/patchy-light-rain-with-thunder.webp",
        "Moderate or heavy rain with thunder": "/weatherIcons/night/moderate-or-heavy-rain-with-thunder.webp",
        
        "Patchy snow possible": "/weatherIcons/night/patchy-snow-possible.webp",
        "Patchy light snow": "/weatherIcons/night/patchy-snow-possible.webp",
        "Light snow showers": "/weatherIcons/night/patchy-snow-possible.webp",
        "Thundery outbreaks possible": "/weatherIcons/night/thundery-outbreaks-possible.webp",
        "Patchy moderate snow": "/weatherIcons/night/patchy-moderate-snow.webp",
        "Moderate or heavy snow showers": "/weatherIcons/night/patchy-moderate-snow.webp",
        "Light showers of ice pellets": "/weatherIcons/night/patchy-moderate-snow.webp",
        "Patchy heavy snow": "/weatherIcons/night/patchy-heavy-snow.webp",
        "Moderate or heavy showers of ice pellets": "/weatherIcons/night/patchy-heavy-snow.webp",
        "Patchy light snow with thunder": "/weatherIcons/night/patchy-light-snow-with-thunder.webp",
        "Moderate or heavy snow with thunder": "/weatherIcons/night/moderate-or-heavy-snow-with-thunder.webp",
        
    }
}

export default weatherUrl;